env:
  browser: true
  es2021: true
extends:
  - google
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins: [
  'svelte3'
]
overrides: [
  {
    files: ['*.svelte'],
    processor: 'svelte3/svelte3'
  }
]
rules: {
  quotes: ['error', 'double'],
  max-len: 0,
  require-jsdoc: 0,
  arrow-parens: 0,
  object-curly-spacing: 0
}